---
# Ref: https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository#configuring-the-template-chooser
blank_issues_enabled: true
contact_links:
  - name: 🙋  Usage Questions
    url: https://github.com/pydeepsar/pydeepsar/discussions
    about: |
      Use DeepSAR Python package's GitHub Discussions to ask "How do I do X with DeepSAR Python package?".
  - name: 📖  Tutorial
    url: https://github.com/pydeepsar/pydeepsar
    about: |
      The DeepSAR Python package tutorial is continually updated and provides an in depth walkthrough
      of how to use the latest release of DeepSAR Python package.
  - name: 📝  DeepSAR Python package Code of Conduct
    url: https://github.com/pydeepsar/pydeepsar/coc/CODE_OF_CONDUCT.md
    about: Expectations for how people will interact with each other on DeepSAR Python package's GitHub.
