---
name: Release

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: write
  issues: write
  pull-requests: write
  # This permission is required for trusted publishing.
  id-token: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    timeout-minutes: 10

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v4

      - uses: conda-incubator/setup-miniconda@v3
        with:
          miniconda-version: "latest"
          mamba-version: "1.*"
          environment-file: conda/dev.yaml
          channels: conda-forge,nodefaults
          channel-priority: true
          activate-environment: pydeepsar
          use-mamba: true
          miniforge-variant: Mambaforge

      - name: Install deps
        run: |
          poetry install

      - name: Run semantic release (for tests)
        if: ${{ github.event_name != 'workflow_dispatch' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          makim release.dry

      - name: Mint token
        id: mint
        uses: tschm/token-mint-action@v1.0.3

      - name: Run semantic release
        if: ${{ github.event_name == 'workflow_dispatch' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: |
          poetry config pypi-token.pypi ${PYPI_TOKEN}
          makim release.ci

      - name: Generate documentation with changes from semantic-release
        run: makim docs.build

      - name: GitHub Pages action
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: >-
            docs/_build/
